loadTimeData.data = {
  bestScore: "最佳 $1 $2 $3",
  bestScoreFlyout: "最高分：$1",
  bestScoreMenuDisplay: "$1 $2",
  cancel: "取消",
  close: "关闭",
  code: "作弊码已激活！",
  codeCheat: "作弊码已激活！$1",
  codeScoring: "本轮积分取消。",
  endlessBestScore: -1,
  endlessDescriptor: "距离",
  endlessModeTitleInline: "无尽：",
  endlessTitle: "无尽",
  endlessUnit: "米",
  fontfamily: "system-ui, sans-serif",
  fontsize: "75%",
  gameCreditsButton: "致谢",
  gameCreditsDialogTitle: "致谢",
  gameMode: "游戏模式修改为 $1",
  gameModeSelectLabel: "游戏模式",
  gameModeSelectLabelDisabled: "游戏模式 (重新启动游戏以修改)",
  gameSettings: "游戏设置",
  highVisibilityActive: false,
  highVisiblityModeToggleLabel: "高可见度",
  howToPlayButton: "玩法",
  howToPlayControllerBoost: "Press RT to use your speed boost",
  howToPlayControllerMovement: "Use the thumbstick or D-pad to steer",
  howToPlayControllerRefresh: "Press LB+RB to restart the game",
  howToPlayDialogTitle: "玩法",
  howToPlayEndless:
    "我不会翻译就不翻译了",
  howToPlayKeyboardBoost: "按 `F` 加速",
  howToPlayKeyboardMovement: "用鼠标或 `WASD` 转向",
  howToPlayKeyboardRefresh: "刷新页面重启游戏",
  howToPlayMouseBoost: "右键加速",
  howToPlayMouseMovement: "移动鼠标转向",
  howToPlayMouseRefresh: "刷新页面重启游戏",
  howToPlayTimeTrial:
    "我不会翻译就不翻译了",
  howToPlayTouchBoost: "Swipe down twice to use your speed boost",
  howToPlayTouchMovement: "Swipe or tap to steer",
  howToPlayTouchRefresh: "Refresh the page to restart the game",
  howToPlayZigZag: "我不会翻译就不翻译了",
  is_windows_xbox_sku: "false",
  keyboardAction: "空格键",
  language: "en",
  lastSelectedMode: "endless",
  lastSelectedPlayer: 4,
  lastSelectedTheme: "surf",
  menuInfo: "开始游戏",
  mouseAction: "双击",
  newBestScore: "New best $1 $2 $3",
  newGame: "Start new game",
  off: "关闭",
  on: "开启",
  overInfo: "再玩一次",
  overTitle: "太棒了！",
  pauseInfo: "继续游戏",
  pauseTitle: "游戏暂停",
  reducedSpeedActive: false,
  reducedSpeedModeToggleLabel: "慢速模式",
  resetAllStats: "重置",
  resetAllStatsDialogText:
    "你确实要重置吗？",
  resetAllStatsDialogTitle: "重置一切",
  share: "分享",
  shareCopy: "复制",
  shareLink: "https://whstu.dpdns.org/game/surf",
  shareLinkCopied: "已复制！",
  skiTheme: "让我们网上滑雪吧",
  specialThanks: "特别感谢：",
  surfTheme: "让我们网上冲浪吧",
  textdirection: "ltr",
  theme: "主题已切换为 $1",
  themeSelectLabel: "主题",
  timetrialBestScore: -1,
  timetrialDescriptor: "时间",
  timetrialModeTitleInline: "限时：",
  timetrialTitle: "限时赛",
  timetrialUnit: "秒",
  touchAction: "double tap",
  zigzagBestScore: -1,
  zigzagDescriptor: "streak",
  zigzagModeTitleInline: "障碍：",
  zigzagTitle: "障碍赛",
  zigzagUnit: "关卡",
};
